[connection]
# Evita que o DNS recebido via DHCP sobrescreva os servidores
ipv4.ignore-auto-dns=true
ipv6.ignore-auto-dns=true

[global-dns]
# Limpa domínios de busca anteriores para evitar conflitos
searches=

[global-dns-domain-*]
# Outras alternativas de DNS

# IPv4
#9.9.9.9		Quad9
#1.1.1.2		Cloudflare
#194.242.2.5		Mullvad
#8.8.8.8		Google

# IPv6
#2620:fe::fe		Quad9
#2606:4700:4700::1112	Cloudflare
#2a07:e340::5		Mullvad
#2001:4860:4860::8888	Google

servers=9.9.9.9,2620:fe::fe,1.1.1.2
