# Usa iwd como backend para gerenciamento Wi‑Fi
[device]
# Backend Wi‑Fi a ser usado (iwd = iNet Wireless Daemon)
wifi.backend=iwd
# Habilita autoconexão em redes conhecidas
wifi.iwd.autoconnect=yes

[connection]
# Desativa power saving para evitar quedas de conexão
wifi.powersave=2
