# NetworkManager — randomiza MAC para privacidade
[device]
# Habilita MAC randomizado durante o scan de redes Wi-Fi
wifi.scan-rand-mac-address=yes

[connection]
# Usa MAC aleatória ao estabelecer conexão Wi-Fi
wifi.cloned-mac-address=random
# Usa MAC aleatória ao estabelecer conexão Ethernet
ethernet.cloned-mac-address=random
