# Inicie processos necessários automaticamente (como daemons de notificações, barras de status, etc.)
# Ou execute seus aplicativos favoritos ao iniciar assim:

exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment QT_QPA_PLATFORMTHEME WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark" 

# exec-once = nm-applet --indicator
exec-once = waybar # blueman-applet
exec-once = kbuildsycoca6
exec-once = /usr/lib/hyprpolkitagent
exec-once = hyprpaper
exec-once = mako
exec-once = /usr/lib/kdeconnectd
