# Veja https://wiki.hypr.land/Configuring/Monitors/
# monitor = name, resolution, position, scale
# hyprctl monitors

monitor=eDP-1,highres@highrr,0x0,1.25
monitor=HDMI-A-1,highres@highrr,auto-left,1.25
# Espelha monitor/tela
# monitor = ,preferred,auto,1,mirror, eDP-1

# desescalar XWayland
xwayland {
  force_zero_scaling = true
}