# Veja https://wiki.hypr.land/Configuring/Permissions/
# Observe que alterações de permissão aqui exigem reinício do Hyprland e não são aplicadas imediatamente
# por motivos de segurança

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow