# Veja https://wiki.hypr.land/Configuring/Window-Rules/ para mais
# Veja https://wiki.hypr.land/Configuring/Workspace-Rules/ para regras de áreas de trabalho

# Exemplo de regra de janela
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignorar pedidos de maximizar de aplicativos. Você provavelmente vai gostar disso.
windowrule = suppressevent maximize, class:.*

# Corrige alguns problemas de arrasto com XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


# WORKSPACE REGRAS

workspace = 1, monitor:"eDP-1", default:true
