########################################################################################
# EDITE ESTA CONFIG DE ACORDO COM AS INSTRUÇÕES DA WIKI.
########################################################################################

# Observe que nem todas as opções/configurações disponíveis estão aqui.
# Para uma lista completa, veja a wiki:
# https://wiki.hypr.land/Configuring/

# Mantenha a ordem estabelecida (a ordem importa!). 
source = ./settings/monitors.conf
source = ./settings/programs.conf
source = ./settings/autostart.conf
source = ./settings/env.conf
source = ./settings/permissions.conf
source = ./settings/look-and-style.conf
source = ./settings/input.conf
source = ./settings/shortcuts.conf
source = ./settings/windows-and-workspaces.conf