[terminal]
# O VT para executar o greeter. Pode ser "next", "current" ou um número
# que designa o VT.
vt = 2

# A sessão padrão, também conhecida como greeter.
[default_session]

# `agreety` é o agetty empacotado/um simulador de login. Você pode substituir `/bin/sh`
# pelo que quiser iniciar, como `sway`.
command = "tuigreet --remember --user-menu --asterisks --time --cmd /home/roneki/.config/river/river-session.sh"

# O usuário que executará o comando. Os privilégios que esse usuário deve ter
# dependem do greeter. Um greeter gráfico pode, por exemplo, exigir que o usuário
# pertença ao grupo `video`.
user = "greeter"
