[main]
term = foot
font = FiraCode Nerd Font Mono:style=Medium:size=18
dpi-aware = yes
pad = 10x0
bold-text-in-bright = no
box-drawings-uses-font-glyphs = yes

[scrollback]
lines = 10000
indicator-position = none

[cursor]
style = beam
blink = no


[colors]
foreground = c9d1d9
background = 2c2c2c 

# Paleta normal
regular0 = 484f58
regular1 = ff7b72
regular2 = 58a6ff
regular3 = d29922
regular4 = 58a6ff
regular5 = bc8cff
regular6 = 39c5cf
regular7 = b1bac4

# Paleta brilhante
bright0 = 6e7681
bright1 = ffa198
bright2 = 79c0ff
bright3 = e3b341
bright4 = 79c0ff
bright5 = bc8cff
bright6 = 39c5cf
bright7 = b1bac4

[mouse]
hide-when-typing = yes
