# limine.conf — configuração do Limine para sistema UEFI
#
# Coloque esse arquivo em esp/EFI/limine/limine.conf
#

timeout: 5

default_entry: 1

/Artix Linux - Kernel linux
    protocol: linux
    kernel_path: boot():/linux/vmlinuz-linux
    cmdline: root=UUID=d45e2eab-2d32-4b50-9dc7-5a841f90791e rw loglevel=3  quiet
    module_path: boot():/linux/intel-ucode.img
    module_path: boot():/linux/initramfs-linux.img
    comment: Kernel linux com microcode Intel + initramfs padrão


/Artix Linux - Kernel linux (fallback)
    protocol: linux
    kernel_path: boot():/linux/vmlinuz-linux
    cmdline: root=UUID=d45e2eab-2d32-4b50-9dc7-5a841f90791e rw loglevel=3  quiet
    module_path: boot():/linux/intel-ucode.img
    module_path: boot():/linux/initramfs-linux-fallback.img
    comment: Kernel linux com initramfs fallback (resgate)


