# ROW = Um ao lado do outro (Laptop direita, HDMI esquerda )
ARRANGE: ROW
ALIGN: TOP

ORDER:
  - "!^HDMI-A-1$" # Monitor LG depois (Esquerda / Posiçao 0)
  - "!^eDP-1$" # Laptop primeiro (Direita / Posição 1)

SCALING: TRUE
AUTO_SCALE: FALSE

SCALE:
  - NAME_DESC: "!^eDP-1$"
    SCALE: 1.5

  - NAME_DESC: "!^HDMI-A-1$"
    SCALE: 1.5

MODE:
  - NAME_DESC: "!^eDP-1$"
    MAX: TRUE

  - NAME_DESC: "!^HDMI-A-1$"
    WIDTH: 1920
    HEIGHT: 1080
    HZ: 75

VRR_OFF:
  - "!^eDP-1$"

LOG_THRESHOLD: INFO
CALLBACK_CMD: 'notify-send -i video-display -t 3000 "Monitor" "${CALLBACK_MSG}"'
LAPTOP_DISPLAY_PREFIX: "eDP"
