###############################################
# PERFIL 1: LAPTOP SOLO
###############################################
[[profile]]
name = "notebook"
exec = ["notify-send 'Shikane' 'Modo: Apenas notebook'"]

    [[profile.output]]
    search = "n=eDP-1"
    enable = true
    mode = "1920x1080@60"
    position = "0,0"
    scale = 1.5



###############################################
# PERFIL 2: CASA (LG Monitor - Estendido)
###############################################
[[profile]]
name = "dual_monitor"
exec = ["notify-send 'Shikane' 'Modo: estendido'"]

    # Laptop
    [[profile.output]]
    search = "n=eDP-1"
    enable = true
    mode = "1920x1080@60Hz"
    position = "0,0"
    scale = 1.5


    # Monitor LG FULL HD
    [[profile.output]]
    search = ["n=HDMI-A-1", "s=0x000147EA", "m=LG FULL HD"]
    enable = true
    mode = "1920x1080@75Hz"
    adaptive_sync = true
    position = "1280,0"
    scale = 1.5



###############################################
# PERFIL 3: PROJETOR/OUTROS (GENÉRICO)
###############################################
[[profile]]
name = "generic_extended"
exec = ["notify-send 'Shikane' 'Modo: estendido (genérico)'"]

    # Laptop
    [[profile.output]]
    search = "n=eDP-1"
    enable = true
    mode = "1920x1080@60Hz"
    position = "0,0"
    scale = 1.5

    # monitor externo
    [[profile.output]]
    search = "n=HDMI"
    enable = true
    mode = "1920x1080@60Hz"
    position = "1920,0"
    scale = 1.5
