# Consulte https://wiki.hypr.land/Configuring/Variables/
# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 5
    gaps_out = 12

    border_size = 0

    # https://wiki.hypr.land/Configuring/Variables/#variable-types para informações sobre cores
    col.active_border = rgba(ffffffee) rgba(2c2c2cee) 35deg
    col.inactive_border = rgba(595959aa)

    # Defina como true para permitir redimensionar janelas clicando e arrastando bordas e espaços
    resize_on_border = true

    # Consulte https://wiki.hypr.land/Configuring/Tearing/ antes de ativar
    allow_tearing = false
    layout = dwindle
}

dwindle {
    # Consulte https://wiki.hypr.land/Configuring/Dwindle-Layout/
	preserve_split = true
	smart_split = false
	smart_resizing = false
}
# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 7
    rounding_power = 2

    # Altere a transparência de janelas focadas e desfocadas
    active_opacity = 1.0
    inactive_opacity = 1.0


    shadow {
        enabled = false
        range = 5
        render_power = 4
        color = rgba(1a1a1aee)
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = false
        size = 3
        passes = 1

        vibrancy = 0.1696
    }
}

# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    # enabled = yes, please :)
     enabled = false
    first_launch_animation = false

    # Animações padrão, veja https://wiki.hypr.land/Configuring/Animations/ para mais

    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1

    animation = global, 1, 10, default
    animation = border, 1, 5.39, easeOutQuint
    animation = windows, 1, 4.79, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
    animation = windowsOut, 1, 1.49, linear, popin 87%
    animation = fadeIn, 1, 1.73, almostLinear
    animation = fadeOut, 1, 1.46, almostLinear
    animation = fade, 1, 3.03, quick
    animation = layers, 1, 3.81, easeOutQuint
    animation = layersIn, 1, 4, easeOutQuint, fade
    animation = layersOut, 1, 1.5, linear, fade
    animation = fadeLayersIn, 1, 1.79, almostLinear
    animation = fadeLayersOut, 1, 1.39, almostLinear
    animation = workspaces, 1, 1.94, almostLinear, fade
    animation = workspacesIn, 1, 1.21, almostLinear, fade
    animation = workspacesOut, 1, 1.94, almostLinear, fade
}

# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Gaps inteligentes" / "Sem gaps quando só"
# descomente todos se quiser usar isso.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]

# Veja https://wiki.hypr.land/Configuring/Dwindle-Layout/ para mais
dwindle {
    pseudotile = true # Chave geral para pseudotile. Ativar está vinculado ao mainMod + P na seção de atalhos abaixo
    preserve_split = true # Provavelmente você vai querer isso
}

# Veja https://wiki.hypr.land/Configuring/Master-Layout/ para mais
master {
    new_status = master xwayland.enabled = true
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = -1 # Defina como 0 ou 1 para desativar os papéis de parede de mascote anime
    disable_hyprland_logo = true # Se true desativa o logo aleatório do hyprland / fundo de anime girl. :(
    vrr = 1 # ativando freesync
    vfr = true

}
